name: Generate Documentation 

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
     
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup compodoc
        run: npm i -g @compodoc/compodoc

      - name: Generate tsds documentation
        run: npm run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: teknowmads/teknowmads.github.io
          publish_dir: ./documentation
          publish_branch: main